name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: aver1y
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Cache citations
      id: cache-citations
      uses: actions/cache@v1
      with:
        path: citation-cache
        key: citation-cache
    - name: Cache node_modules
      id: cache-node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node_modules
    - name: Build
      run: |
        yarn install --network-concurrency 1
        nix-shell -p cabal2nix --run 'cabal2nix . > hormone-therapy-info.nix'
        nix-build
    - name: Build site
      run: |
        result/bin/site rebuild
        touch _site/.nojekyll
    - name: Deploy
      if: success() && github.event_name == 'push'
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: _site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
